# Generated by Django 3.0.4 on 2020-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='SorT',
        ),
        migrations.AddField(
            model_name='info',
            name='Stundent',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='Teacher',
            field=models.BooleanField(default=0),
        ),
    ]
