# Generated by Django 3.0.4 on 2020-04-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200423_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='Stundent',
            new_name='Student',
        ),
    ]
