# Generated by Django 3.0.4 on 2020-04-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200423_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
