# Generated by Django 3.0.4 on 2020-04-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200423_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Teacher',
        ),
    ]
