# Generated by Django 3.0.4 on 2020-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200424_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile',
            field=models.ImageField(default='download.png', upload_to='images/profile'),
        ),
    ]
