# Generated by Django 3.0.4 on 2020-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200424_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
    ]
