# Generated by Django 3.0.4 on 2020-04-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200424_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='profile',
            field=models.ImageField(default='download_40S1UkL.png', upload_to='images/profile/'),
        ),
    ]
