# Generated by Django 3.0.4 on 2020-04-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200424_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Student',
        ),
        migrations.AddField(
            model_name='info',
            name='SorT',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=10),
        ),
    ]
