# Generated by Django 3.0.4 on 2020-04-26 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_auto_20200426_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('stream', models.CharField(choices=[('school', 'school'), ('college', 'college'), ('higher studies', 'higher studies')], max_length=30)),
                ('groupicon', models.ImageField(upload_to='images/group/')),
                ('description', models.CharField(max_length=20)),
                ('grkey', models.TextField(default=1735328, unique=True)),
                ('li', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
