# Generated by Django 3.0.4 on 2020-04-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grkey',
            field=models.TextField(default=9116134, unique=True),
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('li', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='main.Group')),
            ],
        ),
    ]
