# Generated by Django 3.0.4 on 2020-04-27 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_auto_20200427_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grkey',
            field=models.TextField(default=4715514, unique=True),
        ),
        migrations.RemoveField(
            model_name='members',
            name='li',
        ),
        migrations.AddField(
            model_name='members',
            name='li',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
