# Generated by Django 3.0.4 on 2020-04-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200427_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grkey',
            field=models.TextField(default=1666704, unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='li',
            field=models.ManyToManyField(related_name='member', to='main.Group'),
        ),
    ]
