# Generated by Django 3.0.4 on 2020-04-27 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200427_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grkey',
            field=models.TextField(default=2403000, unique=True),
        ),
        migrations.RemoveField(
            model_name='members',
            name='li',
        ),
        migrations.AddField(
            model_name='members',
            name='li',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='main.Group'),
            preserve_default=False,
        ),
    ]
