# Generated by Django 3.0.4 on 2020-04-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200427_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grkey',
            field=models.TextField(default=594002, unique=True),
        ),
        migrations.RemoveField(
            model_name='members',
            name='li',
        ),
        migrations.AddField(
            model_name='members',
            name='li',
            field=models.ManyToManyField(related_name='member', to='main.Group'),
        ),
    ]
