# Generated by Django 3.0.4 on 2020-04-28 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200428_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grkey',
            field=models.TextField(default=1437630, unique=True),
        ),
        migrations.RemoveField(
            model_name='members',
            name='li',
        ),
        migrations.AddField(
            model_name='members',
            name='li',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='main.Group'),
        ),
    ]
