# Generated by Django 3.0.4 on 2020-04-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200428_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grkey',
            field=models.TextField(default=7138814, unique=True),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('li', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='main.Group')),
            ],
        ),
    ]
